remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Audio Examples]
description: [Audio Examples for the paper "Differentiable All-pass Filters for Phase Response Estimation and Automatic Signal Alignment"]
